/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SuppliersRecordIdRouteImport } from './routes/suppliers_.$recordId'
import { Route as AdminOrganizationsOrganizationIdRouteImport } from './routes/admin_.organizations.$organizationId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin_.users.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRecordIdRoute = SuppliersRecordIdRouteImport.update({
  id: '/suppliers_/$recordId',
  path: '/suppliers/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsOrganizationIdRoute =
  AdminOrganizationsOrganizationIdRouteImport.update({
    id: '/admin_/organizations/$organizationId',
    path: '/admin/organizations/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin_/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/suppliers/$recordId': typeof SuppliersRecordIdRoute
  '/admin/organizations/$organizationId': typeof AdminOrganizationsOrganizationIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/suppliers/$recordId': typeof SuppliersRecordIdRoute
  '/admin/organizations/$organizationId': typeof AdminOrganizationsOrganizationIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/suppliers_/$recordId': typeof SuppliersRecordIdRoute
  '/admin_/organizations/$organizationId': typeof AdminOrganizationsOrganizationIdRoute
  '/admin_/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/invitations'
    | '/login'
    | '/settings'
    | '/suppliers'
    | '/suppliers/$recordId'
    | '/admin/organizations/$organizationId'
    | '/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/invitations'
    | '/login'
    | '/settings'
    | '/suppliers'
    | '/suppliers/$recordId'
    | '/admin/organizations/$organizationId'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/invitations'
    | '/login'
    | '/settings'
    | '/suppliers'
    | '/suppliers_/$recordId'
    | '/admin_/organizations/$organizationId'
    | '/admin_/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  InvitationsRoute: typeof InvitationsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRoute
  SuppliersRecordIdRoute: typeof SuppliersRecordIdRoute
  AdminOrganizationsOrganizationIdRoute: typeof AdminOrganizationsOrganizationIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers_/$recordId': {
      id: '/suppliers_/$recordId'
      path: '/suppliers/$recordId'
      fullPath: '/suppliers/$recordId'
      preLoaderRoute: typeof SuppliersRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/organizations/$organizationId': {
      id: '/admin_/organizations/$organizationId'
      path: '/admin/organizations/$organizationId'
      fullPath: '/admin/organizations/$organizationId'
      preLoaderRoute: typeof AdminOrganizationsOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/users/$userId': {
      id: '/admin_/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  InvitationsRoute: InvitationsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRoute,
  SuppliersRecordIdRoute: SuppliersRecordIdRoute,
  AdminOrganizationsOrganizationIdRoute: AdminOrganizationsOrganizationIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
