// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScrapGo.Core.Modules.QuickbaseEngine.Infrastructure.Persistence;

#nullable disable

namespace ScrapGo.Core.Modules.QuickbaseEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QuickbaseDbContext))]
    [Migration("20260929050117_InitialQuickbaseEngine")]
    partial class InitialQuickbaseEngine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("quickbase")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScrapGo.Core.Modules.QuickbaseEngine.Domain.Caching.QueryCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fetched_at");

                    b.Property<string>("QueryHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_hash");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_json");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.Property<string>("TableId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("table_id");

                    b.HasKey("Id")
                        .HasName("pk_query_caches");

                    b.HasIndex("FetchedAt")
                        .HasDatabaseName("ix_query_caches_fetched_at");

                    b.HasIndex("QueryHash")
                        .IsUnique()
                        .HasDatabaseName("ux_query_caches_query_hash");

                    b.HasIndex("TableId")
                        .HasDatabaseName("ix_query_caches_table_id");

                    b.ToTable("query_caches", "quickbase");
                });
#pragma warning restore 612, 618
        }
    }
}
